### ISSUE TITLE
Selector of ContractDefinition targets 50 Assets max. (= 50 ContractOffers max. per Definition)

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#2064]
# Bug Report

## Describe the Bug

The AssetSelector (Criteria) of a ContractDefinition never creates catalog offers for more than 50 Assets.

### Expected Behavior

- Catalog contains all offers for each contract definition

### Observed Behavior

- Catalog contains not more than 50 offers for contract definitions with selector targeting > 50 assets 

## Steps to Reproduce
1. Create 51 Assets
2. Create a Contract Definition targeting all 51 Assets
3. Request the Catalog with another connector
4. -> Catalog contains only 50 offers

## Context Information

- Used version `0.0.1-20221006-SNAPSHOT`

## Detailed Description

see comment in code

_From ContractOfferServiceImpl.java_

```java

    @Override
    @NotNull
    public Stream<ContractOffer> queryContractOffers(ContractOfferQuery query) {
        var agent = agentService.createFor(query.getClaimToken());

        return definitionService.definitionsFor(agent, query.getRange())
                .flatMap(definition -> {
                    var assetFilterQuery = QuerySpec.Builder.newInstance()
                            .filter(concat(definition.getSelectorExpression().getCriteria().stream(), query.getAssetsCriteria().stream()).collect(Collectors.toList())).build();
                    var assets = assetIndex.queryAssets(assetFilterQuery); // filter targets 50 assets max.
                    return Optional.of(definition.getContractPolicyId())
                            .map(policyStore::findById)
                            .map(policy -> assets.map(asset -> createContractOffer(definition, policy.getPolicy(), asset)))
                            .orElseGet(Stream::empty);
                });
    }

```

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by ndr-brt** [comment]
This should has been fixed with #2018

**Comment by DominikPinsel** [comment]
> This should has been fixed with #2018

Just tested it with `0.0.1-20221012-SNAPSHOT` and I still get the same behavior.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by ndr-brt** [comment]
> > This should has been fixed with #2018
> 
> Just tested it with `0.0.1-20221012-SNAPSHOT` and I still get the same behavior.
> 
> Dominik Pinsel [dominik.pinsel@mercedes-benz.com](mailto:dominik.pinsel@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

If the catalog request has been made without specifying the `limit` parameter that's correct, because it has a "safe" default value of 50, if you instead used an higher limit value and got only 50 results, that's a bug

**Comment by ndr-brt** [comment]
Removed the `bug` label because this doesn't appear to be a bug: if the `limit` parameter is not passed there's a default value of 50 used to prevent server overloading.

**Comment by DominikPinsel** [comment]
> Removed the `bug` label because this doesn't appear to be a bug: if the `limit` parameter is not passed there's a default value of 50 used to prevent server overloading.

Maybe I need to explain it better.

```java
var assetFilterQuery = QuerySpec.Builder.newInstance()
                            .filter(concat(definition.getSelectorExpression().getCriteria().stream(), query.getAssetsCriteria().stream()).collect(Collectors.toList())).build();
var assets = assetIndex.queryAssets(assetFilterQuery); // filter targets 50 assets max.
```

As you see this asset filter, that is created per contract definition, has no limit defined. Therefore, a single contract definition will always create 50 offers max. and the set limit will not be able to make a difference here.

**Comment by ndr-brt** [comment]
I think this snippet you posted is not updated, there were some works done on the now called `ContractOfferResolverImpl`.

Looking closer, the problem is not there, is in the implementation of the `AssetIndex.countAssets`, that should ignore `limit` and `offset` parameters to get the asset count.
@paullatzelsperger wdyt?
